// Code generated by cmd/reset. DO NOT EDIT!

package audit

func (s *FileProvider) Reset() {
	if s == nil {
		return
	}

	s.filePath = ""
	if s.entries != nil {
		s.entries = s.entries[:0]
	}
}

func (s *HTTPProvider) Reset() {
	if s == nil {
		return
	}

	if s.client != nil {
		if resetter, ok := any(s.client).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
	s.endpoint = ""
}

func (s *Action) Reset() {
	if s == nil {
		return
	}

	s.Timestamp = 0
	if resetter, ok := any(&s.ActionType).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if s.UserID != nil {
		*s.UserID = ""
	}
	s.URL = ""
}
