// Code generated by cmd/reset. DO NOT EDIT!

package services

func (s *ShortenerService) Reset() {
	if s == nil {
		return
	}

	s.baseURL = ""
	if s.providers != nil {
		s.providers = s.providers[:0]
	}
}

func (s *UserService) Reset() {
	if s == nil {
		return
	}

	if s.secret != nil {
		s.secret = s.secret[:0]
	}
}
