// Code generated by cmd/reset. DO NOT EDIT!

package internal

func (s *AppConfig) Reset() {
	if s == nil {
		return
	}

	s.Addr = ""
	s.BaseURL = ""
	s.FilePath = ""
	s.DatabaseDSN = ""
	if s.Secret != nil {
		s.Secret = s.Secret[:0]
	}
	s.AuditFile = ""
	s.AuditURL = ""
}
